apiVersion: v1
kind: ReplicationController
metadata:
  name: wasapp
  namespace: bogdan
spec:
  replicas: 3
  selector:
    app: wasapp
  template:
    metadata:
      name: wasapp
      labels:
        app: wasapp
    spec:
      containers:
      - name: wasapp-img
        image: wasapp-img
        imagePullPolicy: Never
        ports:
          - containerPort: 9080
          - containerPort: 9443
