apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitrepo
  namespace: bogdan
  labels:
    app: gitrepo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitrepo
  template:
    metadata:
      labels:
        app: gitrepo
    
    spec:
      containers:
      - image: nginx:alpine
        name: web-server
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: html
        gitRepo:
          repository: https://github.com/luksa/kubia-website-example.git
          revision: master
          directory: .
